
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

install: ## Install Python deps into the active env
	pip install -r requirements.txt

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

train: ## Train with default config
	python src/train.py

analyze: ## Post-hoc analysis (src/analyze.py)
	python src/analyze.py

rename: ## Set the project name everywhere:  make rename NAME=my-project
	@echo "$(NAME)" | grep -Eq '^[A-Za-z0-9._-]+$$' || { echo "usage: make rename NAME=<project-name>   (letters, digits, . _ -)"; exit 1; }
	sed -i '1s/.*/# $(NAME)/' README.md
	sed -i 's/^name: .*/name: $(NAME)/' environment.yaml
	sed -i 's/^PROJECT_NAME=.*/PROJECT_NAME=$(NAME)/' .env.example
	@if [ -f .env ]; then sed -i 's/^PROJECT_NAME=.*/PROJECT_NAME=$(NAME)/' .env; fi
	@echo "project name -> $(NAME)  (README title, environment.yaml, .env.example/.env PROJECT_NAME)"
